# Generated by Django 5.2.4 on 2025-07-05 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('compatible_brand', models.CharField(choices=[('apple', 'Apple iPhone'), ('samsung', 'Samsung Galaxy'), ('huawei', 'Huawei'), ('xiaomi', 'Xiaomi'), ('oppo', 'OPPO'), ('vivo', 'Vivo'), ('oneplus', 'OnePlus'), ('google', 'Google Pixel'), ('sony', 'Sony Xperia'), ('lg', 'LG'), ('nokia', 'Nokia'), ('motorola', 'Motorola'), ('universal', 'Universal')], default='universal', max_length=20)),
                ('product_type', models.CharField(choices=[('case', 'Phone Case'), ('cover', 'Phone Cover'), ('screen_protector', 'Screen Protector'), ('charger', 'Charger'), ('cable', 'Cable'), ('power_bank', 'Power Bank'), ('headphones', 'Headphones'), ('car_mount', 'Car Mount'), ('wireless_charger', 'Wireless Charger'), ('pop_socket', 'Pop Socket'), ('ring_holder', 'Ring Holder'), ('wallet_case', 'Wallet Case')], default='case', max_length=20)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category')),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['id', 'slug'], name='shop_produc_id_f21274_idx')],
            },
        ),
    ]
